# Generated by Django 3.2.5 on 2022-05-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
